testproj/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from users.models import Item

urlpatterns = [
    path('',TemplateView.as_view(template_name = 'users/home.html'),{'items':Item.objects.all()},name = 'home'),
    path('admin/', admin.site.urls),
    path('users/',include('users.urls')),
    path('users/',include('django.contrib.auth.urls')),
]

users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/',views.SignUp.as_view(), name = 'signup'),
    path('add/<int:item_id>',views.addFood, name = "addFood"),
    path('cart/', views.showCart, name = "cart"),
    path('success/', views.confirmOrder, name = "confirmOrder"),
    path('orders/', views.displayFood, name = "displayFood"),
    path('paymentPage/', views.paymentPortal, name = "paymentPortal"),
    path('deleteorder/<int:cart_id>',views.deleteCartOrder,name = "deleteCartOrder"),
]

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils import timezone

# Create your models here.
class CustomUser(AbstractUser):
    firstname = models.CharField(max_length = 50, null = True)
    lastname = models.CharField(max_length = 50, null = True)
    def __str__(self):
        return self.email

class Item(models.Model):
    name = models.CharField(max_length = 100, null = True)
    descr = models.CharField(max_length = 200, null = True)
    price = models.FloatField(default = 0)

class Orders(models.Model):
    customer = models.ForeignKey(CustomUser, on_delete = models.CASCADE)
    item = models.ForeignKey(Item, on_delete = models.CASCADE, related_name = "conf_item", null = True)

class CartOrders(models.Model):
    customer = models.ForeignKey(CustomUser, on_delete = models.CASCADE)
    item = models.ForeignKey(Item, on_delete = models.CASCADE, related_name = "cart_item", null = True)

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import CustomUser, Orders

class CustomUserCreationForm(UserCreationForm):
    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('username','email','firstname','lastname')

class CustomUserChangeForm(UserChangeForm):
    class Meta(UserChangeForm):
        model = CustomUser
        fields = ('username','email')

class customDateInput(forms.DateInput):
    input_type = "date"

class CredentialForm(forms.Form):
    credit_card = forms.IntegerField(required = True)
    cvv = forms.IntegerField(widget = forms.PasswordInput(), required = True)
    expiry = forms.CharField()
    company = forms.CharField(max_length = 200)
    address = forms.CharField(max_length = 200)
    city = forms.CharField(max_length = 100)
    state = forms.CharField(max_length = 100)
    zipcode = forms.IntegerField()
    country = forms.CharField(max_length = 100)

users/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from .forms import CustomUserCreationForm, CredentialForm
from .models import Orders, CustomUser, CartOrders, Item
from authorizenet import apicontractsv1
from authorizenet.apicontrollers import createTransactionController
import imp
import random
from django.http import HttpResponseRedirect
from django.shortcuts import reverse

# Create your views here.
class SignUp(generic.CreateView):
    form_class = CustomUserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'users/signup.html'

def addFood(request,item_id):
    customer = CustomUser.objects.get(username__exact = request.user.username)
    item = Item.objects.get(pk = item_id)
    cartorder = CartOrders(customer = customer, item = item)
    cartorder.save()
    cartorders = customer.cartorders_set.all()
    return render(request,"users/cart.html",{'cartorders':cartorders})

def confirmOrder(request):
    customer = CustomUser.objects.get(username__exact = request.user.username)
    cartorders = customer.cartorders_set.all()
    totalprice = 0
    for cartorder in cartorders:
        totalprice += cartorder.item.price
    for cartorder in cartorders:
        order = Orders(customer = customer, item = cartorder.item)
        order.save()
    cartorders.delete()
    return render(request,"users/success.html",{'customer':customer, 'totalprice':totalprice})

def displayFood(request):
    customer = CustomUser.objects.get(username__exact = request.user.username)
    return render(request,'users/ordlist.html',{'customer':customer})

def deleteCartOrder(request, cart_id):
    customer = CustomUser.objects.get(username__exact = request.user.username)
    order = customer.cartorders_set.get(pk = cart_id)
    item_name = order.item.name
    order.delete()
    return render(request,"users/deleteorders.html",{'item_name':item_name})

def showCart(request):
    customer = CustomUser.objects.get(username__exact = request.user.username)
    cartorders = customer.cartorders_set.all()
    return render(request,"users/cart.html",{'cartorders':cartorders})

def paymentPortal(request):
    if request.method == "POST":
        form = CredentialForm(request.POST)
        if form.is_valid():
            data = form.cleaned_data
            data['customer'] = CustomUser.objects.get(username__exact = request.user.username)
            print(data)
            amount = 0
            customer = CustomUser.objects.get(username__exact = request.user.username)
            for cartorder in customer.cartorders_set.all():
                amount += cartorder.item.price
            if authorize_credit_card(amount, data).messages.resultCode == "Ok":
                return HttpResponseRedirect(reverse("users:confirmOrder"))
    else:
        form = CredentialForm()
        return render(request,"users/paymentform.html",{'form':form})

# CONSTANTS = imp.load_source('modulename', 'constants.py')

def authorize_credit_card(amount, data):
    """
    Authorize a credit card (without actually charging it)
    """

    # Create a merchantAuthenticationType object with authentication details
    # retrieved from the constants file
    merchantAuth = apicontractsv1.merchantAuthenticationType()
    merchantAuth.name = '3t2LGu4AR2Nb'
    merchantAuth.transactionKey = '78eC2pb4J42cu2WL'

    # Create the payment data for a credit card
    creditCard = apicontractsv1.creditCardType()
    creditCard.cardNumber = str(data['credit_card'])
    creditCard.expirationDate = data['expiry']
    #creditCard.cardCode = data['cvv']

    # Add the payment data to a paymentType object
    payment = apicontractsv1.paymentType()
    payment.creditCard = creditCard

    # Create order information
    invoiceNum = str(random.randint(1,1000))
    order = apicontractsv1.orderType()
    order.invoiceNumber = invoiceNum
    order.description = "Food Items"

    # Set the customer's Bill To address
    zipcode = str(data['zipcode'])
    customerAddress = apicontractsv1.customerAddressType()
    customerAddress.firstName = data['customer'].firstname
    customerAddress.lastName = data['customer'].lastname
    customerAddress.company = data['company']
    customerAddress.address = data['address']
    customerAddress.city = data['city']
    customerAddress.state = data['state']
    customerAddress.zip = zipcode
    customerAddress.country = data['country']

    # Set the customer's identifying information
    custId = str(data['customer'].pk)
    customerData = apicontractsv1.customerDataType()
    customerData.type = "individual"
    customerData.id = custId
    customerData.email = data['customer'].email

    # Add values for transaction settings
    duplicateWindowSetting = apicontractsv1.settingType()
    duplicateWindowSetting.settingName = "duplicateWindow"
    duplicateWindowSetting.settingValue = "600"
    settings = apicontractsv1.ArrayOfSetting()
    settings.setting.append(duplicateWindowSetting)

    # build the array of line items
    line_items = apicontractsv1.ArrayOfLineItem()

    # setup individual line items
    for cartitem in data['customer'].cartorders_set.all():
        itemId = str(cartitem.item.pk)
        temp_item = apicontractsv1.lineItemType()
        temp_item.itemId = itemId
        temp_item.name = cartitem.item.name
        temp_item.descr = cartitem.item.descr
        temp_item.quantity = 1
        temp_item.unitPrice = cartitem.item.price
        line_items.append(temp_item)


    # Create a transactionRequestType object and add the previous objects to it.
    transactionrequest = apicontractsv1.transactionRequestType()
    transactionrequest.transactionType = "authOnlyTransaction"
    transactionrequest.amount = amount
    transactionrequest.payment = payment
    transactionrequest.order = order
    transactionrequest.billTo = customerAddress
    transactionrequest.customer = customerData
    transactionrequest.transactionSettings = settings
    transactionrequest.lineItems = line_items

    # Assemble the complete transaction request
    createtransactionrequest = apicontractsv1.createTransactionRequest()
    createtransactionrequest.merchantAuthentication = merchantAuth
    createtransactionrequest.refId = "MerchantID-0001"
    createtransactionrequest.transactionRequest = transactionrequest
    # Create the controller
    createtransactioncontroller = createTransactionController(
        createtransactionrequest)
    createtransactioncontroller.execute()

    response = createtransactioncontroller.getresponse()

    if response is not None:
        # Check to see if the API request was successfully received and acted upon
        if response.messages.resultCode == "Ok":
            # Since the API request was successful, look for a transaction response
            # and parse it to display the results of authorizing the card
            if hasattr(response.transactionResponse, 'messages') is True:
                print(
                    'Successfully created transaction with Transaction ID: %s'
                    % response.transactionResponse.transId)
                print('Transaction Response Code: %s' %
                      response.transactionResponse.responseCode)
                print('Message Code: %s' %
                      response.transactionResponse.messages.message[0].code)
                print('Description: %s' % response.transactionResponse.
                      messages.message[0].description)
            else:
                print('Failed Transaction.')
                if hasattr(response.transactionResponse, 'errors') is True:
                    print('Error Code:  %s' % str(response.transactionResponse.
                                                  errors.error[0].errorCode))
                    print(
                        'Error message: %s' %
                        response.transactionResponse.errors.error[0].errorText)
        # Or, print errors if the API request wasn't successful
        else:
            print('Failed Transaction.')
            if hasattr(response, 'transactionResponse') is True and hasattr(
                    response.transactionResponse, 'errors') is True:
                print('Error Code: %s' % str(
                    response.transactionResponse.errors.error[0].errorCode))
                print('Error message: %s' %
                      response.transactionResponse.errors.error[0].errorText)
            else:
                print('Error Code: %s' %
                      response.messages.message[0]['code'].text)
                print('Error message: %s' %
                      response.messages.message[0]['text'].text)
    else:
        print('Null Response.')

    return response

users/templates/users/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
        <link rel="stylesheet" type="text/css" href="../../static/users/style.css" />
        <link href="https://fonts.googleapis.com/css?family=Josefin+Sans" rel="stylesheet">
        <title>{% block title %}{% endblock %}</title>
        <style>
            html, body {
                font-family: 'Josefin Sans', sans-serif;
            }
            body {
                background-image: url("../../static/users/img/rest.jpg");
            }
            .transparent {
                background-color: rgba(0,0,0,0.5);
                color: white;
            }
            input {
                border-radius: 20px;
            }

            .descr {
                width: 100%;
                height: 20%;
            }
        </style>
    </head>
    <body>
        <div class="row main-block">
            <div class="offset-sm-1 col-sm-10 offset-sm-1 jumbotron text-center transparent">
        {% block content %}
        {% endblock %}
            </div>
        </div>
    </body>
</html>

users/templates/users/cart.html
{% extends 'users/base.html' %}
{% block title %} Your cart {% endblock %}
{% block content %}
    {% if cartorders %}
        <h1>Your cart</h1>
        <table class = "table table-dark table-striped">
            <thead>
                <tr>
                    <th>Item</th>
                    <th>Type</th>
                    <th>Price</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for cartitem in cartorders %}
                    <tr>
                        <td>{{ cartitem.item.name }}</td>
                        <td>{{ cartitem.item.descr }}</td>
                        <td>{{ cartitem.item.price }}</td>
                        <td><a href = "{% url 'users:deleteCartOrder' cartitem.pk %}" class = "btn btn-danger">Delete</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        Move to <a href = "{% url 'users:paymentPortal' %}" class = "btn btn-success">payment portal</a> | <a href = "{% url 'home' %}">Order more</a>
    {% else %}
        <h3>Your cart is empty! Click <a href = "{% url 'home' %}">here</a> to add items to your cart</h3>
    {% endif %}
{% endblock %}

users/templates/users/deleteorders.html
{% extends 'users/base.html' %}
{% block title %}Order history wiped{% endblock %}
{% block content %}
    <h1 class = "display-4">Item {{ item_name }} has been deleted from your cart</h1>
    Return to <a href = "{% url 'home' %}" class = "btn btn-success">Home</a>
{% endblock %}

users/templates/users/home.html
{% extends 'users/base.html' %}
{% block title %} Home {% endblock %}
{% block content %}
    {% if user.is_authenticated %}
        <h3>Hi {{ user.username }}! What would you like to order today?</h3><br />
        {% for item in items %}
            <a href = "{% url 'users:addFood' item.pk %}" class = "btn btn-danger rounded-pill" style = "margin: 10px 10px;">{{ item.name }}</a><br />
        {% endfor %}
        <footer class="page-footer align-items-center">
            <a href="{% url 'logout' %}" class = "btn btn-danger">Logout</a> | 
            <a href = "{% url 'users:displayFood' %}" class = "btn btn-success">Your orders</a> |
            <a href = "{% url 'users:cart' %}" class = "btn btn-success">Your cart</a>
        </footer>
    {% else %}
        <h3 style = "padding-bottom: 25px;">Welcome to foodies!</h3>
        <a href="{% url 'login' %}" class = "btn btn-success">Login</a> | <a href="{% url 'users:signup' %}" class = "btn btn-info">Signup</a>
    {% endif %}
{% endblock %}

users/templates/users/ordlist.html
{% extends 'users/base.html' %}
{% block title %} Your orders {% endblock %}
{% block content %}
    {% if customer.orders_set.all %}
        <h3>You bought:</h3>
        <br />
        <table class = "table table-dark table-hover">
            <thead>
                <tr>
                    <th>Item Name</th>
                    <th>Price</th>
                    <th>Type</th>
                    <th>Ordered At</th>
                </tr>
            </thead>
        {% for item in customer.orders_set.all %}
            <tr>
                <td>{{ item.item_name }}</td>
                <td>{{ item.price }}</td>
                <td>{{ item.type_of_food }}</td>
                <td>{{ item.order_time }}</td>
            </tr>
        {% endfor %}
        </table>
        <p>Want to order something else? Click <a href = "{% url 'home' %}">here</a></p><br />
    {% else %}
        <h3>Your order list is empty! Order <a href = "{% url 'home' %}">here</a></h3>
    {% endif %}
{% endblock %}

users/templates/users/paymentform.html
{% extends 'users/base.html' %}
{% block title %}Payment information{% endblock %}
{% block content %}
    {% if error %}
        {% block error %}
        <div class = "alert alert-danger" role = "alert">
            Credentials didn't match with our database. Please enter correct information!
        </div>
        {% endblock %}
    {% endif %}
    <form action = "{% url 'users:paymentPortal' %}" method = "POST" class = "form-group">
        {% csrf_token %}
        {{ form.as_p }}
        <input type = "submit" value = "Submit" class = "btn btn-primary" /> | 
        <a href = "{% url 'users:cart' %}" class = "btn btn-secondary">Go Back</a>
    </form>
{% endblock %}

users/templates/users/signup.html
{% extends 'users/base.html' %}
{% block title %} Signup form {% endblock %}
{% block content %}
    <h1>Registration form</h1>
    <form method="POST">
        <div class="form-group">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class = "btn btn-success">Sign up</button>
        </div>
    </form>
{% endblock %}

users/templates/users/success.html
{% extends 'users/base.html' %}
{% block title %} Confirmation {% endblock %}
{% block content %}
    <h3> Hurray {{ customer.username }}! You ordered &#8377 {{ totalprice }} worth of items</h3>
    <p> You can go back to <a href = "{% url 'home' %}">homepage</a> to order more items</p>
{% endblock %}

users/templates/users/temp.html
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
        <title>Dashboard</title>
    </head>
    <body>
        <div class = "container">
            <div class = "row">
                <div class = "col-xs-6 offset-col-xs-3">
                    <div id = "NonVegCarousel" class = "carousel slide carousel-fade" data-ride = "carousel">
                        <ol class="carousel-indicators">
                            <li data-target="#NonVegCarousel" data-slide-to="0" class="active"></li>
                            <li data-target="#NonVegCarousel" data-slide-to="1"></li>
                            <li data-target="#NonVegCarousel" data-slide-to="2"></li>
                        </ol>
                        <div class = "carousel-inner">
                            <div class = "carousel-item active">
                                <img src = "../../static/users/img/nvpizza.png" class = "d-block w-100" alt = "First slide" />
                                <div class = "carousel-caption d-none d-md-block text-dark">
                                    <h3>Chicken Mexicana</h3>
                                    <p>Chicken rashers topped with anchovies and onions</p>
                                    <h4>Price: &#8377 400</h4>
                                </div>
                            </div>
                            <div class="carousel-item">
                                <img src="../../static/users/img/nvrolls.png" class="d-block w-100" alt="Second slide" />
                                <div class = "carousel-caption d-none d-md-block text-dark">
                                    <h3>Chicken tandoor roll</h3>
                                    <p>Soft and tender chicken roasted to perfection</p>
                                    <h4>Price: &#8377 80</h4>
                                </div>
                            </div>
                            <div class = "carousel-item">
                                <img src = "../../static/users/img/nvburger.png" class = "d-block w-100" alt = "Third slide" />
                                <div class = "carousel-caption d-none d-md-block text-dark">
                                    <h3>Chicken Burger</h3>
                                    <p>Chicken rashers topped with anchovies and onions</p>
                                    <h4>Price: &#8377 100</h4>
                                </div>
                            </div>
                        </div>
                        <a class="carousel-control-prev" href="#NonVegCarousel" role="button" data-slide="prev">
                            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                        </a>
                        <a class="carousel-control-next" href="#NonVegCarousel" role="button" data-slide="next">
                            <span class="carousel-control-next-icon" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </body>